apiVersion: apps/v1
kind: Deployment
metadata:
  name: Cloud-Devops-Nanodegree-Capstone
  labels:
    app: Cloud-Devops-Nanodegree-Capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Cloud-Devops-Nanodegree-Capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: Cloud-Devops-Nanodegree-Capstone
    spec:
      containers:
        - image: shoumaw/Cloud-Devops-Nanodegree-Capstone
          imagePullPolicy: Always
          name: Cloud-Devops-Nanodegree-Capstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: Cloud-Devops-Nanodegree-Capstone
  labels:
    app: Cloud-Devops-Nanodegree-Capstone
spec:
  type: LoadBalancer
  selector:
    app: Cloud-Devops-Nanodegree-Capstone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
